
# My stuff converted from .bash_profile
if [ -f $HOME/.dotfiles/bash/colors ]; then
  . $HOME/.dotfiles/bash/colors
  HR="--------------------------------------------------------------------------------"
  echo -e "\n${CYAN}${HR}"

  echo -e "${yellow}"  
  if [ -f ~/.motd ]; then cat ~/.motd; fi

  echo -e "${purple}$(fortune -s)\n"
  echo -e "${CYAN}${HR}\n"
  echo -e "${green}$(date +'%A %Y %B %d - %r') ${NC}\n"
fi

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export LESS=-iXFR

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="zendoodles"

# Make history useful again...
export HISTCONTROL=erasedups
declare -x HISTIGNORE='??:clear:exit:history'
export HISTSIZE=50000
export HISTFILESIZE=1000000

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git last-working-dir npm phing sudo)

source $ZSH/oh-my-zsh.sh

# User configuration

export PATH="$HOME/.local/bin:/usr/games:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:$HOME/Code/bin:/usr/include/php/bin:$HOME/pear/bin:/usr/local/mysql/bin:$HOME/.composer/vendor/bin:/opt/local/bin:/opt/local/sbin:$HOME/bin:$HOME/dotfiles/bin"
# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# FFS... use vim please.
export VISUAL=vim
export EDITOR="$VISUAL"

# Allow the use of # as a comment character on the cli.
setopt interactivecomments

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
if [ -f $HOME/.dotfiles/bash/aliases ]; then
  . $HOME/.dotfiles/bash/aliases
fi

# Make sure the shell can find homebrew.
eval "$(/opt/homebrew/bin/brew shellenv)"

# Add my keys to the ssh agent; passwords are pulled from the keychain.
# The --apple-load-keychain option is unique to MacOS.

ssh-add --apple-load-keychain
